seed: Don't apply a flux Secret if no SSH key is specified
In the case where apply sources the flux manifests from the git repository, we
were unconditionally trying to apply the flux Secret even if no deploy key had
been specified from the user, which was leading to a validation error (because,
then, the resolved go template wasn't a valid Secret:

```
INFO[2019-09-12T15:07:14+01:00] Starting                                      resource="install:flux:flux-git-deploy-secret"
/tmp/flux-git-deploy-secret.yamlczTSIk2Q3e
error: error validating "/tmp/flux-git-deploy-secret.yamlczTSIk2Q3e": error validating data: unknown object type "nil" in Secret.data.identity; if you choose to ignore these errors, turn validation off with --validate=false
```

Skip applying the flux Secret if the user hasn't given us any.